// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd5zX5GrREdKRi0epkj5hdV_XiSAYwjHw',
    appId: '1:1042579510740:android:f781c57366ac6d9f833241',
    messagingSenderId: '1042579510740',
    projectId: 'led-pixels-control',
    storageBucket: 'led-pixels-control.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP0IR5X3pReyQlU_YgnZD89WolYHYrQBQ',
    appId: '1:1042579510740:ios:2a23fb2a1cf5053e833241',
    messagingSenderId: '1042579510740',
    projectId: 'led-pixels-control',
    storageBucket: 'led-pixels-control.appspot.com',
    iosClientId: '1042579510740-2db8cpb32m3ban6nva1bs8gb516giuca.apps.googleusercontent.com',
    iosBundleId: 'led.strip.control',
  );
}
